/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MockFollowModule,
  MockFollowModuleInterface,
} from "../MockFollowModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "followNFTTokenId",
        type: "uint256",
      },
    ],
    name: "followModuleTransferHook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "initializeFollowModule",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "follower",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "followNFTTokenId",
        type: "uint256",
      },
    ],
    name: "isFollowing",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "follower",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "processFollow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061038e806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80630e096ae1146100515780633cb22cc414610067578063451c3d0c146100755780639713958a146100a1575b600080fd5b61006561005f3660046101cb565b50505050565b005b61006561005f366004610225565b61008c610083366004610269565b60019392505050565b60405190151581526020015b60405180910390f35b6100b46100af36600461029e565b6100c1565b60405161009891906102ea565b606060006100d18385018561033f565b905080600114610141576040517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152601960248201527f4d6f636b466f6c6c6f774d6f64756c653a20696e76616c696400000000000000604482015260640160405180910390fd5b50506040805160008152602081019091529392505050565b803573ffffffffffffffffffffffffffffffffffffffff8116811461017d57600080fd5b919050565b60008083601f84011261019457600080fd5b50813567ffffffffffffffff8111156101ac57600080fd5b6020830191508360208285010111156101c457600080fd5b9250929050565b600080600080606085870312156101e157600080fd5b6101ea85610159565b935060208501359250604085013567ffffffffffffffff81111561020d57600080fd5b61021987828801610182565b95989497509550505050565b6000806000806080858703121561023b57600080fd5b8435935061024b60208601610159565b925061025960408601610159565b9396929550929360600135925050565b60008060006060848603121561027e57600080fd5b8335925061028e60208501610159565b9150604084013590509250925092565b6000806000604084860312156102b357600080fd5b83359250602084013567ffffffffffffffff8111156102d157600080fd5b6102dd86828701610182565b9497909650939450505050565b600060208083528351808285015260005b81811015610317578581018301518582016040015282016102fb565b81811115610329576000604083870101525b50601f01601f1916929092016040019392505050565b60006020828403121561035157600080fd5b503591905056fea26469706673582212209483b742e451898a0a7e1be539ec47f0057e3ea330904ad94096a78e28014fab64736f6c634300080a0033";

type MockFollowModuleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockFollowModuleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockFollowModule__factory extends ContractFactory {
  constructor(...args: MockFollowModuleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "MockFollowModule";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MockFollowModule> {
    return super.deploy(overrides || {}) as Promise<MockFollowModule>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MockFollowModule {
    return super.attach(address) as MockFollowModule;
  }
  connect(signer: Signer): MockFollowModule__factory {
    return super.connect(signer) as MockFollowModule__factory;
  }
  static readonly contractName: "MockFollowModule";
  public readonly contractName: "MockFollowModule";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockFollowModuleInterface {
    return new utils.Interface(_abi) as MockFollowModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockFollowModule {
    return new Contract(address, _abi, signerOrProvider) as MockFollowModule;
  }
}
