/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  RevertCollectModule,
  RevertCollectModuleInterface,
} from "../RevertCollectModule";

const _abi = [
  {
    inputs: [],
    name: "CollectNotAllowed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "pubId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "initializePublicationCollectModule",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "referrerProfileId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "collector",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "pubId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "processCollect",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610270806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063c233f9511461003b578063e49c3dda14610076575b600080fd5b610060610049366004610106565b505060408051600081526020810190915292915050565b60405161006d9190610159565b60405180910390f35b6100896100843660046101ae565b61008b565b005b6040517fad4cf0a300000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60008083601f8401126100cf57600080fd5b50813567ffffffffffffffff8111156100e757600080fd5b6020830191508360208285010111156100ff57600080fd5b9250929050565b6000806000806060858703121561011c57600080fd5b8435935060208501359250604085013567ffffffffffffffff81111561014157600080fd5b61014d878288016100bd565b95989497509550505050565b600060208083528351808285015260005b818110156101865785810183015185820160400152820161016a565b81811115610198576000604083870101525b50601f01601f1916929092016040019392505050565b60008060008060008060a087890312156101c757600080fd5b86359550602087013573ffffffffffffffffffffffffffffffffffffffff811681146101f257600080fd5b94506040870135935060608701359250608087013567ffffffffffffffff81111561021c57600080fd5b61022889828a016100bd565b979a969950949750929593949250505056fea2646970667358221220096aabe41a56fb5e91575d594eb80433e6929f6ddbd2f4c464eab7dd46db56cf64736f6c634300080a0033";

type RevertCollectModuleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RevertCollectModuleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RevertCollectModule__factory extends ContractFactory {
  constructor(...args: RevertCollectModuleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "RevertCollectModule";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<RevertCollectModule> {
    return super.deploy(overrides || {}) as Promise<RevertCollectModule>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): RevertCollectModule {
    return super.attach(address) as RevertCollectModule;
  }
  connect(signer: Signer): RevertCollectModule__factory {
    return super.connect(signer) as RevertCollectModule__factory;
  }
  static readonly contractName: "RevertCollectModule";
  public readonly contractName: "RevertCollectModule";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RevertCollectModuleInterface {
    return new utils.Interface(_abi) as RevertCollectModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RevertCollectModule {
    return new Contract(address, _abi, signerOrProvider) as RevertCollectModule;
  }
}
